language: node_js
node_js:
- '8.0'
deploy:
  provider: npm
  email: remcohaszing@gmail.com
  api_key:
    secure: L8TXwrcHMsceqDhMjz+2TUdYHr8wVmT9eMagKZwlN01OFI94Oho80IKlojXL1hRPQOolybOFbaJo9ZAnLx04j3QM3zUSf5k3dRZfHuT0QNLAGhzRjRiE+ii8a/4z4ni4jwQFfiSPxrWjEuIx4LI/2IX16INha6yLLBo+83uuVMjxY6RS2zj4gX4TXIrbNCF9dyrorjXel4TxojaZ6Y/x5EfiYRRaLsQAsw3IbJaNjPAhF6BTPATpgjBMgvrDAZOlqIeRBNkNgqtrytvEFH7gw22cSksbjr/IHVS5XRZvNac6r5lWDw29nbVvnG/5BvUoG0fGoj05hL+aAleV7w/grKPj6Io2CUtdW0RJkLFX72TZ72d+L9UnWEisfw+Rqgy/STh1AhusSZPrkHLpQrfqd6HqqZFmE+vTX4+2nyiKV1QJ6rVzKSmo/MhkR7uvCOus6Egy5rDZGXThc2VrDhUxCnIJNrEQcrdqPZywTys9DMBr0jQ7+vbiw+Hik48JoIDQ0tbaYrfJBJ8UPbgo3/TQ9MlOziB2CU6QIiTB335mv7wpa+J21gMlcsz8AP7CuAGGWLdaeWu8WRtLfqWVY+wmo2KmI1BGJw4f+rs4kOawqUMtyDs4JC3WqNh05h/Vklh6/IBMQCguaudH0EiZhB9end1/79HLSUFQ7uWgoVgdlg8=
  on:
    tags: true
    repo: appsemble/material-ui-background
